<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//PT_BR" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<!-- <!DOCTYPE MATRICULA [
  <!ELEMENT MATRICULA (IDENTIFICACAO,HORARIO,NOME,SERIE,PROFESSOR,,QUESTAO1,COMENTARIO1,NOTAQUESTAO1,QUESTAO2,COMENTARIO2,NOTAQUESTAO2,QUESTAO3,COMENTARIO3,NOTAQUESTAO3,QUESTAO4,COMENTARIO4,NOTAQUESTAO4,QUESTAO5,COMENTARIO5,NOTAQUESTAO5,QUESTAO6,COMENTARIO6,NOTAQUESTAO6,APROVADO)>
  <!ELEMENT IDENTIFICACAO    (#PCDATA)>
  <!ELEMENT HORARIO    (#PCDATA)>
  <!ELEMENT NOME    (#PCDATA)>
  <!ELEMENT SERIE    (#PCDATA)>
  <!ELEMENT PROFESSOR    (#PCDATA)>
  <!ELEMENT QUESTAO1    (#PCDATA)>
  <!ELEMENT COMENTARIO1    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO1    (#PCDATA)>
  <!ELEMENT QUESTAO2    (#PCDATA)>
  <!ELEMENT COMENTARIO2    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO2    (#PCDATA)>
  <!ELEMENT QUESTAO3    (#PCDATA)>
  <!ELEMENT COMENTARIO3    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO3    (#PCDATA)>  
  <!ELEMENT QUESTAO4    (#PCDATA)>
  <!ELEMENT COMENTARIO4    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO4    (#PCDATA)>  
  <!ELEMENT QUESTAO5    (#PCDATA)>
  <!ELEMENT COMENTARIO5    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO5    (#PCDATA)>  
  <!ELEMENT QUESTAO6    (#PCDATA)>
  <!ELEMENT COMENTARIO6    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO6    (#PCDATA)>  
  <!ELEMENT APROVADO   (#PCDATA)>

]> -->
<MATRICULA>
	<IDENTIFICACAO>60a418c85668368841ed180187ce60d2_08_08_2013_135404</IDENTIFICACAO>
	<APROVADO>0</APROVADO>
	<NOME>Elson campos</NOME>
	<SERIE>8 série B</SERIE>
	<PROFESSOR>José Nunes</PROFESSOR>
	<HORARIO>1</HORARIO>
	<QUESTAO1>Acredito que as possibilidades</QUESTAO1>
	<COMENTARIO1>errou errou feio</COMENTARIO1>
	<NOTAQUESTAO1>1</NOTAQUESTAO1>
	<QUESTAO2>Supondo que em total acordo</QUESTAO2>
	<COMENTARIO2>Supondo que em total acordo</COMENTARIO2>
	<NOTAQUESTAO2></NOTAQUESTAO2>
	<QUESTAO3>Está claro que algumas formas de ver</QUESTAO3>
	<COMENTARIO3>Vejo com bons olhos</COMENTARIO3>
	<NOTAQUESTAO3></NOTAQUESTAO3>
	<QUESTAO4>Porque não entendeu o sistema</QUESTAO4>
	<COMENTARIO4></COMENTARIO4>
	<NOTAQUESTAO4></NOTAQUESTAO4>
	<QUESTAO5>as ultimas linhas são as do fim</QUESTAO5>
	<COMENTARIO5></COMENTARIO5>
	<NOTAQUESTAO5></NOTAQUESTAO5>
	<QUESTAO6>Vejo com bons olhos</QUESTAO6>
	<COMENTARIO6></COMENTARIO6>
	<NOTAQUESTAO6></NOTAQUESTAO6>
</MATRICULA>
<!-- by Oliveira M.J.N [Xamaleon v.0.1][soordle.org][eadgames.com.br] -->