<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//PT_BR" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<!-- <!DOCTYPE MATRICULA [
  <!ELEMENT MATRICULA (IDENTIFICACAO,HORARIO,NOME,SERIE,PROFESSOR,,QUESTAO1,COMENTARIO1,NOTAQUESTAO1,QUESTAO2,COMENTARIO2,NOTAQUESTAO2,QUESTAO3,COMENTARIO3,NOTAQUESTAO3,QUESTAO4,COMENTARIO4,NOTAQUESTAO4,QUESTAO5,COMENTARIO5,NOTAQUESTAO5,QUESTAO6,COMENTARIO6,NOTAQUESTAO6,APROVADO)>
  <!ELEMENT IDENTIFICACAO    (#PCDATA)>
  <!ELEMENT HORARIO    (#PCDATA)>
  <!ELEMENT NOME    (#PCDATA)>
  <!ELEMENT SERIE    (#PCDATA)>
  <!ELEMENT PROFESSOR    (#PCDATA)>
  <!ELEMENT QUESTAO1    (#PCDATA)>
  <!ELEMENT COMENTARIO1    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO1    (#PCDATA)>
  <!ELEMENT QUESTAO2    (#PCDATA)>
  <!ELEMENT COMENTARIO2    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO2    (#PCDATA)>
  <!ELEMENT QUESTAO3    (#PCDATA)>
  <!ELEMENT COMENTARIO3    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO3    (#PCDATA)>  
  <!ELEMENT QUESTAO4    (#PCDATA)>
  <!ELEMENT COMENTARIO4    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO4    (#PCDATA)>  
  <!ELEMENT QUESTAO5    (#PCDATA)>
  <!ELEMENT COMENTARIO5    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO5    (#PCDATA)>  
  <!ELEMENT QUESTAO6    (#PCDATA)>
  <!ELEMENT COMENTARIO6    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO6    (#PCDATA)>  
  <!ELEMENT APROVADO   (#PCDATA)>

]> -->
<MATRICULA>
	<IDENTIFICACAO>69b9a8251871b04e1ca4817d741e54af_08_08_2013_145114</IDENTIFICACAO>
	<APROVADO>1</APROVADO>
	<NOME>Eliseo souza</NOME>
	<SERIE>4c</SERIE>
	<PROFESSOR>Valderson</PROFESSOR>
	<HORARIO>1</HORARIO>
	
	<QUESTAO1>fasdfasf</QUESTAO1>
	<COMENTARIO1></COMENTARIO1>
	<NOTAQUESTAO1>10</NOTAQUESTAO1>
	
	<QUESTAO2>ddgfgsdf</QUESTAO2>
	<COMENTARIO2></COMENTARIO2>
	<NOTAQUESTAO2>10</NOTAQUESTAO2>
	<QUESTAO3>dfgsdfg</QUESTAO3>
	<COMENTARIO3></COMENTARIO3>
	<NOTAQUESTAO3>10</NOTAQUESTAO3>
	<QUESTAO4>dfgsdfg</QUESTAO4>
	<COMENTARIO4></COMENTARIO4>
	<NOTAQUESTAO4>10</NOTAQUESTAO4>
	<QUESTAO5>sdfg</QUESTAO5>
	<COMENTARIO5></COMENTARIO5>
	<NOTAQUESTAO5>2</NOTAQUESTAO5>
	<QUESTAO6>sdfgsdfgsdfgsdfgsdfgsdf sdfg sdfg sdfgsdfgsdf sdfgsdfgsd sdfgsdf sdfg sdfgsdfgsdfg sdfgsdfg sd sdfgsdfg</QUESTAO6>
	<COMENTARIO6></COMENTARIO6>
	<NOTAQUESTAO6>5</NOTAQUESTAO6>
</MATRICULA>
<!-- by Oliveira M.J.N [Xamaleon v.0.1][soordle.org][eadgames.com.br] -->