<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//PT_BR" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<!-- <!DOCTYPE MATRICULA [
  <!ELEMENT MATRICULA (IDENTIFICACAO,HORARIO,NOME,SERIE,PROFESSOR,,QUESTAO1,COMENTARIO1,NOTAQUESTAO1,QUESTAO2,COMENTARIO2,NOTAQUESTAO2,QUESTAO3,COMENTARIO3,NOTAQUESTAO3,QUESTAO4,COMENTARIO4,NOTAQUESTAO4,QUESTAO5,COMENTARIO5,NOTAQUESTAO5,QUESTAO6,COMENTARIO6,NOTAQUESTAO6,APROVADO)>
  <!ELEMENT IDENTIFICACAO    (#PCDATA)>
  <!ELEMENT HORARIO    (#PCDATA)>
  <!ELEMENT NOME    (#PCDATA)>
  <!ELEMENT SERIE    (#PCDATA)>
  <!ELEMENT PROFESSOR    (#PCDATA)>
  <!ELEMENT QUESTAO1    (#PCDATA)>
  <!ELEMENT COMENTARIO1    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO1    (#PCDATA)>
  <!ELEMENT QUESTAO2    (#PCDATA)>
  <!ELEMENT COMENTARIO2    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO2    (#PCDATA)>
  <!ELEMENT QUESTAO3    (#PCDATA)>
  <!ELEMENT COMENTARIO3    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO3    (#PCDATA)>  
  <!ELEMENT QUESTAO4    (#PCDATA)>
  <!ELEMENT COMENTARIO4    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO4    (#PCDATA)>  
  <!ELEMENT QUESTAO5    (#PCDATA)>
  <!ELEMENT COMENTARIO5    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO5    (#PCDATA)>  
  <!ELEMENT QUESTAO6    (#PCDATA)>
  <!ELEMENT COMENTARIO6    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO6    (#PCDATA)>  
  <!ELEMENT APROVADO   (#PCDATA)>

]> -->
<MATRICULA>
	<IDENTIFICACAO>eda1fa74033f5ed80c400910a0a71374_08_08_2013_140538</IDENTIFICACAO>
	<APROVADO>0</APROVADO>
	<NOME>Valter santos</NOME>
	<SERIE>4d</SERIE>
	<PROFESSOR>Adelson</PROFESSOR>
	<HORARIO>2</HORARIO>
	
	<QUESTAO1>asdfasdfasd</QUESTAO1>
	<COMENTARIO1>teste de comentario2</COMENTARIO1>
	<NOTAQUESTAO1>1</NOTAQUESTAO1>
	
	<QUESTAO2>asrtertsdfsdfg</QUESTAO2>
	<COMENTARIO2>comentario 2</COMENTARIO2>
	<NOTAQUESTAO2>0</NOTAQUESTAO2>
	<QUESTAO3>llfghklfgkhlfk</QUESTAO3>
	<COMENTARIO3>asdfasdfasdf</COMENTARIO3>
	<NOTAQUESTAO3>1</NOTAQUESTAO3>
	<QUESTAO4>rtibmndfn</QUESTAO4>
	<COMENTARIO4>asdfasdf</COMENTARIO4>
	<NOTAQUESTAO4>2</NOTAQUESTAO4>
	<QUESTAO5>mmmsfsdfmsd</QUESTAO5>
	<COMENTARIO5>asdfasdf</COMENTARIO5>
	<NOTAQUESTAO5>3</NOTAQUESTAO5>
	<QUESTAO6>jjjjsdfsdfsdn</QUESTAO6>
	<COMENTARIO6>asdfasdfasdf</COMENTARIO6>
	<NOTAQUESTAO6>3</NOTAQUESTAO6>
</MATRICULA>
<!-- by Oliveira M.J.N [Xamaleon v.0.1][soordle.org][eadgames.com.br] -->