<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//PT_BR" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<!-- <!DOCTYPE MATRICULA [
  <!ELEMENT MATRICULA (IDENTIFICACAO,HORARIO,NOME,SERIE,PROFESSOR,,QUESTAO1,QUESTAO2,QUESTAO3,QUESTAO4,QUESTAO5,QUESTAO6APROVADO)>
  <!ELEMENT IDENTIFICACAO    (#PCDATA)>
  <!ELEMENT HORARIO    (#PCDATA)>
  <!ELEMENT NOME    (#PCDATA)>
  <!ELEMENT SERIE    (#PCDATA)>
  <!ELEMENT PROFESSOR    (#PCDATA)>
  <!ELEMENT QUESTAO1    (#PCDATA)>
  <!ELEMENT QUESTAO2    (#PCDATA)>
  <!ELEMENT QUESTAO3    (#PCDATA)>
  <!ELEMENT QUESTAO4    (#PCDATA)>
  <!ELEMENT QUESTAO5    (#PCDATA)>
  <!ELEMENT QUESTAO6    (#PCDATA)>
  <!ELEMENT APROVADO   (#PCDATA)>

]> -->
<MATRICULA>
	<IDENTIFICACAO>f866ae7b50c36af10973eb8b01dfde61_07_08_2013_165856</IDENTIFICACAO>
	<APROVADO>0</APROVADO>
	<NOME>Manoel</NOME>
	<SERIE>7C</SERIE>
	<PROFESSOR>Marocs</PROFESSOR>
	<HORARIO>0</HORARIO>
	<QUESTAO1>muitas coisas</QUESTAO1>
	<QUESTAO2>sim claro</QUESTAO2>
	<QUESTAO3>dualidade</QUESTAO3>
	<QUESTAO4>entendimento</QUESTAO4>
	<QUESTAO5>o que tem?</QUESTAO5>
	<QUESTAO6>NEMHUMA</QUESTAO6>
</MATRICULA>
<!-- by Oliveira M.J.N [Xamaleon v.0.1][soordle.org][eadgames.com.br] -->