<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//PT_BR" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<!-- <!DOCTYPE MATRICULA [
  <!ELEMENT MATRICULA (IDENTIFICACAO,HORARIO,NOME,SERIE,PROFESSOR,,QUESTAO1,COMENTARIO1,NOTAQUESTAO1,QUESTAO2,COMENTARIO2,NOTAQUESTAO2,QUESTAO3,COMENTARIO3,NOTAQUESTAO3,QUESTAO4,COMENTARIO4,NOTAQUESTAO4,QUESTAO5,COMENTARIO5,NOTAQUESTAO5,QUESTAO6,COMENTARIO6,NOTAQUESTAO6,APROVADO)>
  <!ELEMENT IDENTIFICACAO    (#PCDATA)>
  <!ELEMENT HORARIO    (#PCDATA)>
  <!ELEMENT NOME    (#PCDATA)>
  <!ELEMENT SERIE    (#PCDATA)>
  <!ELEMENT PROFESSOR    (#PCDATA)>
  <!ELEMENT QUESTAO1    (#PCDATA)>
  <!ELEMENT COMENTARIO1    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO1    (#PCDATA)>
  <!ELEMENT QUESTAO2    (#PCDATA)>
  <!ELEMENT COMENTARIO2    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO2    (#PCDATA)>
  <!ELEMENT QUESTAO3    (#PCDATA)>
  <!ELEMENT COMENTARIO3    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO3    (#PCDATA)>  
  <!ELEMENT QUESTAO4    (#PCDATA)>
  <!ELEMENT COMENTARIO4    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO4    (#PCDATA)>  
  <!ELEMENT QUESTAO5    (#PCDATA)>
  <!ELEMENT COMENTARIO5    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO5    (#PCDATA)>  
  <!ELEMENT QUESTAO6    (#PCDATA)>
  <!ELEMENT COMENTARIO6    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO6    (#PCDATA)>  
  <!ELEMENT APROVADO   (#PCDATA)>

]> -->
<MATRICULA>
	<IDENTIFICACAO>007214764583854201bc5587d9c21306_09_08_2013_150109</IDENTIFICACAO>
	<APROVADO>0</APROVADO>
	<NOME>Aluno teste</NOME>
	<SERIE>7 série A</SERIE>
	<PROFESSOR>Heródoto Barbeiro</PROFESSOR>
	<HORARIO>0</HORARIO>
	
	<QUESTAO1>Minha fala para esta questão é de que ...</QUESTAO1>
	<COMENTARIO1></COMENTARIO1>
	<NOTAQUESTAO1></NOTAQUESTAO1>
	
	<QUESTAO2>ler em voz alta torna o leitura mais ......</QUESTAO2>
	<COMENTARIO2></COMENTARIO2>
	<NOTAQUESTAO2></NOTAQUESTAO2>
	<QUESTAO3>Ambiguidade no sentido amplo da palavra nada mais é do que .....</QUESTAO3>
	<COMENTARIO3></COMENTARIO3>
	<NOTAQUESTAO3></NOTAQUESTAO3>
	<QUESTAO4>Além de entender o que está escrito precisamos ir um pouco mais além da simples ....</QUESTAO4>
	<COMENTARIO4></COMENTARIO4>
	<NOTAQUESTAO4></NOTAQUESTAO4>
	<QUESTAO5>Nas últimas linhas percebemos que a descrição ....</QUESTAO5>
	<COMENTARIO5></COMENTARIO5>
	<NOTAQUESTAO5></NOTAQUESTAO5>
	<QUESTAO6>Pergunta ficou incompleta professor</QUESTAO6>
	<COMENTARIO6></COMENTARIO6>
	<NOTAQUESTAO6></NOTAQUESTAO6>
</MATRICULA>
<!-- by Oliveira M.J.N [Xamaleon v.0.1][soordle.org][eadgames.com.br] -->