<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//PT_BR" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<!-- <!DOCTYPE MATRICULA [
  <!ELEMENT MATRICULA (IDENTIFICACAO,HORARIO,NOME,SERIE,PROFESSOR,,QUESTAO1,COMENTARIO1,NOTAQUESTAO1,QUESTAO2,COMENTARIO2,NOTAQUESTAO2,QUESTAO3,COMENTARIO3,NOTAQUESTAO3,QUESTAO4,COMENTARIO4,NOTAQUESTAO4,QUESTAO5,COMENTARIO5,NOTAQUESTAO5,QUESTAO6,COMENTARIO6,NOTAQUESTAO6,APROVADO)>
  <!ELEMENT IDENTIFICACAO    (#PCDATA)>
  <!ELEMENT HORARIO    (#PCDATA)>
  <!ELEMENT NOME    (#PCDATA)>
  <!ELEMENT SERIE    (#PCDATA)>
  <!ELEMENT PROFESSOR    (#PCDATA)>
  <!ELEMENT QUESTAO1    (#PCDATA)>
  <!ELEMENT COMENTARIO1    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO1    (#PCDATA)>
  <!ELEMENT QUESTAO2    (#PCDATA)>
  <!ELEMENT COMENTARIO2    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO2    (#PCDATA)>
  <!ELEMENT QUESTAO3    (#PCDATA)>
  <!ELEMENT COMENTARIO3    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO3    (#PCDATA)>  
  <!ELEMENT QUESTAO4    (#PCDATA)>
  <!ELEMENT COMENTARIO4    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO4    (#PCDATA)>  
  <!ELEMENT QUESTAO5    (#PCDATA)>
  <!ELEMENT COMENTARIO5    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO5    (#PCDATA)>  
  <!ELEMENT QUESTAO6    (#PCDATA)>
  <!ELEMENT COMENTARIO6    (#PCDATA)>
  <!ELEMENT NOTAQUESTAO6    (#PCDATA)>  
  <!ELEMENT APROVADO   (#PCDATA)>

]> -->
<MATRICULA>
	<IDENTIFICACAO>5c2910c36a6ecd9a66a81c28099b53d1_09_08_2013_151351</IDENTIFICACAO>
	<APROVADO>0</APROVADO>
	<NOME>Aluno de teste 2</NOME>
	<SERIE>8 B</SERIE>
	<PROFESSOR>Demógenes</PROFESSOR>
	<HORARIO>1</HORARIO>
	
	<QUESTAO1>assunto polêmico esse</QUESTAO1>
	<COMENTARIO1></COMENTARIO1>
	<NOTAQUESTAO1>0</NOTAQUESTAO1>
	
	<QUESTAO2>Sim claro</QUESTAO2>
	<COMENTARIO2></COMENTARIO2>
	<NOTAQUESTAO2>0</NOTAQUESTAO2>
	<QUESTAO3>duplo sentido?</QUESTAO3>
	<COMENTARIO3></COMENTARIO3>
	<NOTAQUESTAO3>0</NOTAQUESTAO3>
	<QUESTAO4>não entendi</QUESTAO4>
	<COMENTARIO4></COMENTARIO4>
	<NOTAQUESTAO4>0</NOTAQUESTAO4>
	<QUESTAO5>quais linhas?</QUESTAO5>
	<COMENTARIO5></COMENTARIO5>
	<NOTAQUESTAO5>0</NOTAQUESTAO5>
	<QUESTAO6></QUESTAO6>
	<COMENTARIO6></COMENTARIO6>
	<NOTAQUESTAO6>1</NOTAQUESTAO6>
</MATRICULA>
<!-- by Oliveira M.J.N [Xamaleon v.0.1][soordle.org][eadgames.com.br] -->